title: "RELATE Test Quiz"
description: |

    # RELATE Test Quiz

rules:
    # (Things behind '#' hash marks are comments.)
    # Allow students to start two attempts at the quiz before the deadline.
    # After that, only allow access to previously started quizzes.

    start:
    -
        if_after: 2015-03-06 23:59:00
        if_has_role: [student, ta, instructor]
        if_has_fewer_sessions_than: 2
        may_start_new_session: True
        may_list_existing_sessions: True

    -
        may_start_new_session: False
        may_list_existing_sessions: True

    # Allow students to submit quiz answers before the deadline.
    # After the deadline, the quiz becomes read-only. (The 'modify'
    # permission goes away.)

    access:
    -
        if_after: 2015-03-06 23:59:02
        permissions: [view, submit_answer, end_session, see_correctness]

    -
        permissions: [view, see_correctness, see_answer_after_submission]

    # Record grades under the machine-readable name 'test_quiz'.
    # If there is more than one grade, use the maximum.

    grade_identifier: hello_world_task
    grade_aggregation_strategy: max_grade

    grading:
    -   
        if_completed_before: end_week 1
        credit_percent: 100

    -
        if_completed_before: end_week 2
        credit_percent: 65

    -
        credit_percent: 50

pages:

-
    type: PythonCodeQuestionWithHumanTextFeedback
    id: hgtext
    access_rules:
        add_permissions:
            - change_answer
    value: 5
    human_feedback_percentage: 100
    is_optional_page: false
    timeout: 10
    prompt: |

        Tasks
        -----

        ### 0\. Create a file

        mandatory

        Using Puppet, create a file in `/tmp`.

        Requirements:

        -   File path is `/tmp/school`
        -   File permission is `0744`
        -   File owner is `www-data`
        -   File group is `www-data`
        -   File contains `I love Puppet`

        Example:

        ```
        root@6712bef7a528:~# puppet-lint --version
        puppet-lint 2.5.2
        root@6712bef7a528:~# puppet-lint 0-create_a_file.pp
        root@6712bef7a528:~#
        root@6712bef7a528:~# puppet apply 0-create_a_file.pp
        Notice: Compiled catalog for 6712bef7a528.ec2.internal in environment production in 0.04 seconds
        Notice: /Stage[main]/Main/File[school]/ensure: defined content as '{md5}f1b70c2a42a98d82224986a612400db9'
        Notice: Finished catalog run in 0.03 seconds
        root@6712bef7a528:~#
        root@6712bef7a528:~# ls -l /tmp/school
        -rwxr--r-- 1 www-data www-data 13 Mar 19 23:12 /tmp/school
        root@6712bef7a528:~# cat /tmp/school
        I love Puppetroot@6712bef7a528:~#

        ```

        **Repo:**

        -   GitHub repository: `alx-system_engineering-devops`
        -   Directory: `0x0A-configuration_management`
        -   File: `0-create_a_file.pp`

         Done? Help Check your code Get a sandbox
            
    rubric: |

            Has something interesting to say.

-
    type: PythonCodeQuestionWithHumanTextFeedback
    id: hgtext1
    access_rules:
        add_permissions:
            - change_answer
    value: 5
    human_feedback_percentage: 100
    is_optional_page: false
    timeout: 10
    prompt: |
            
            Tasks
            -----
            
            ### 1\. Install a package

            mandatory

            Using Puppet, install `puppet-lint`.

            Requirements:

            -   Install `puppet-lint`
            -   Version must be `2.5.0`

            Example:

            ```
            root@d391259bf577:/# puppet apply 1-install_a_package.pp
            Notice: Compiled catalog for d391259bf577 in environment production in 0.14 seconds
            Notice: Applied catalog in 0.20 seconds
            root@d391259bf577:/# gem list

            *** LOCAL GEMS ***

            puppet-lint (2.5.0)
            root@d391259bf577:/#

            ```

            **Repo:**

            -   GitHub repository: `alx-system_engineering-devops`
            -   Directory: `0x0A-configuration_management`
            -   File: `1-install_a_package.pp`

             Done? Help Check your code Get a sandbox

    rubric: |
            
            Has something interesting to say.

-
    type: PythonCodeQuestionWithHumanTextFeedback
    id: hgtext2
    access_rules:
        add_permissions:
            - change_answer
    value: 5
    human_feedback_percentage: 100
    is_optional_page: false
    timeout: 10
    prompt: |

            Tasks
            -----
            
            ### 2\. Execute a command

            mandatory

            Using Puppet, create a manifest that kills a process named `killmenow`.

            Requirements:

            -   Must use the `exec` Puppet resource
            -   Must use `pkill`

            Example:

            Terminal #0 - starting my process

            ```
            root@d391259bf577:/# cat killmenow
            #!/bin/bash
            while [[ true ]]
            do
                sleep 2
            done

            root@d391259bf577:/# ./killmenow

            ```

            Terminal #1 - executing my manifest

            ```
            root@d391259bf577:/# puppet apply 2-execute_a_command.pp
            Notice: Compiled catalog for d391259bf577.hsd1.ca.comcast.net in environment production in 0.01 seconds
            Notice: /Stage[main]/Main/Exec[killmenow]/returns: executed successfully
            Notice: Finished catalog run in 0.10 seconds
            root@d391259bf577:/#

            ```

            Terminal #0 - process has been terminated

            ```
            root@d391259bf577:/# ./killmenow
            Terminated
            root@d391259bf577:/#

            ```

            **Repo:**

            -   GitHub repository: `alx-system_engineering-devops`
            -   Directory: `0x0A-configuration_management`
            -   File: `2-execute_a_command.pp`

    rubric: |

            Has something interesting to say.



completion_text: |

        You have successfully completed the test exam!
